# coding: utf-8

"""
    API Settings

    At BlueSnap, we look at payments a little differently. Our Payment Orchestration Platform helps businesses accept payments globally and is designed to increase revenue and reduces costs. We provide a comprehensive back-end solutions that simplifies the complexity of payments, managing the full process from start to finish.  BlueSnap supports payments through multiple sales channels such as online and mobile sales, marketplaces, subscriptions, invoice payments and manual orders through a virtual terminal. And for businesses looking for embedded payments, we offer white-labeled payments for platforms with automated underwriting and onboarding that supports marketplaces and split payments.  And with one integration and contract, businesses can sell in over 200 geographies with access to local acquiring in 47 countries, 110+ currencies and 100+ global payment types, including popular eWallets, automated accounts receivable, world-class fraud protection and chargeback management, built-in solutions for regulation and tax compliance, and unified global reporting to help businesses grow.  With a US headquarters in Waltham, MA, and EU headquarters in Dublin, Ireland, BlueSnap is backed by world-class private equity investors including Great Hill Partners and Parthenon Capital Partners.   Learn more at BlueSnap.com

    The version of the OpenAPI document: 8976-Tools
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from blue_snap_python_sdk.pydantic.vendor_update_vendor_request_payout_info import VendorUpdateVendorRequestPayoutInfo
from blue_snap_python_sdk.pydantic.vendor_update_vendor_request_vendor_agreement import VendorUpdateVendorRequestVendorAgreement
from blue_snap_python_sdk.pydantic.vendor_update_vendor_request_vendor_principal import VendorUpdateVendorRequestVendorPrincipal

class VendorUpdateVendorRequest(BaseModel):
    email: typing.Optional[str] = Field(None, alias='email')

    name: typing.Optional[str] = Field(None, alias='name')

    first_name: typing.Optional[str] = Field(None, alias='firstName')

    last_name: typing.Optional[str] = Field(None, alias='lastName')

    address: typing.Optional[str] = Field(None, alias='address')

    city: typing.Optional[str] = Field(None, alias='city')

    zip: typing.Optional[str] = Field(None, alias='zip')

    country: typing.Optional[str] = Field(None, alias='country')

    phone: typing.Optional[str] = Field(None, alias='phone')

    state: typing.Optional[str] = Field(None, alias='state')

    tax_id: typing.Optional[int] = Field(None, alias='taxId')

    vendor_url: typing.Optional[str] = Field(None, alias='vendorUrl')

    ipn_url: typing.Optional[str] = Field(None, alias='ipnUrl')

    default_payout_currency: typing.Optional[str] = Field(None, alias='defaultPayoutCurrency')

    vendor_principal: typing.Optional[VendorUpdateVendorRequestVendorPrincipal] = Field(None, alias='vendorPrincipal')

    payout_info: typing.Optional[VendorUpdateVendorRequestPayoutInfo] = Field(None, alias='payoutInfo')

    vendor_agreement: typing.Optional[VendorUpdateVendorRequestVendorAgreement] = Field(None, alias='vendorAgreement')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
