# coding: utf-8

"""
    API Settings

    At BlueSnap, we look at payments a little differently. Our Payment Orchestration Platform helps businesses accept payments globally and is designed to increase revenue and reduces costs. We provide a comprehensive back-end solutions that simplifies the complexity of payments, managing the full process from start to finish.  BlueSnap supports payments through multiple sales channels such as online and mobile sales, marketplaces, subscriptions, invoice payments and manual orders through a virtual terminal. And for businesses looking for embedded payments, we offer white-labeled payments for platforms with automated underwriting and onboarding that supports marketplaces and split payments.  And with one integration and contract, businesses can sell in over 200 geographies with access to local acquiring in 47 countries, 110+ currencies and 100+ global payment types, including popular eWallets, automated accounts receivable, world-class fraud protection and chargeback management, built-in solutions for regulation and tax compliance, and unified global reporting to help businesses grow.  With a US headquarters in Waltham, MA, and EU headquarters in Dublin, Ireland, BlueSnap is backed by world-class private equity investors including Great Hill Partners and Parthenon Capital Partners.   Learn more at BlueSnap.com

    The version of the OpenAPI document: 8976-Tools
    Generated by: https://konfigthis.com
"""

from blue_snap_python_sdk.paths.recurring_ondemand_subscription_id.post import CreateMerchantManagedChargeRaw
from blue_snap_python_sdk.paths.recurring_ondemand.post import CreateMerchantManagedSubscriptionRaw
from blue_snap_python_sdk.paths.recurring_subscriptions.post import CreateNewRaw
from blue_snap_python_sdk.paths.recurring_subscriptions_subscription_id.get import GetSpecificRaw
from blue_snap_python_sdk.paths.recurring_subscriptions_subscription_id_switch_charge_amount.get import GetSwitchChargeAmountRaw
from blue_snap_python_sdk.paths.recurring_subscriptionsparameters.get import ListAllSubscriptionsRaw
from blue_snap_python_sdk.paths.subscription_id_chargesparameters.get import ListChargesRaw
from blue_snap_python_sdk.paths.recurring_subscriptions_subscription_id.put import UpdateSubscriptionRaw


class SubscriptionApiRaw(
    CreateMerchantManagedChargeRaw,
    CreateMerchantManagedSubscriptionRaw,
    CreateNewRaw,
    GetSpecificRaw,
    GetSwitchChargeAmountRaw,
    ListAllSubscriptionsRaw,
    ListChargesRaw,
    UpdateSubscriptionRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
