# coding: utf-8

"""
    API Settings

    At BlueSnap, we look at payments a little differently. Our Payment Orchestration Platform helps businesses accept payments globally and is designed to increase revenue and reduces costs. We provide a comprehensive back-end solutions that simplifies the complexity of payments, managing the full process from start to finish.  BlueSnap supports payments through multiple sales channels such as online and mobile sales, marketplaces, subscriptions, invoice payments and manual orders through a virtual terminal. And for businesses looking for embedded payments, we offer white-labeled payments for platforms with automated underwriting and onboarding that supports marketplaces and split payments.  And with one integration and contract, businesses can sell in over 200 geographies with access to local acquiring in 47 countries, 110+ currencies and 100+ global payment types, including popular eWallets, automated accounts receivable, world-class fraud protection and chargeback management, built-in solutions for regulation and tax compliance, and unified global reporting to help businesses grow.  With a US headquarters in Waltham, MA, and EU headquarters in Dublin, Ireland, BlueSnap is backed by world-class private equity investors including Great Hill Partners and Parthenon Capital Partners.   Learn more at BlueSnap.com

    The version of the OpenAPI document: 8976-Tools
    Generated by: https://konfigthis.com
"""

from blue_snap_python_sdk.paths.transactions_approval.put import ApproveMerchantTransaction
from blue_snap_python_sdk.paths.transactions_pending_refund_transaction_id.delete import CancelPendingRefund
from blue_snap_python_sdk.paths.batch_transactions.post import CreateBatchTransaction
from blue_snap_python_sdk.paths.alt_transactions.post import CreateSofortTransaction
from blue_snap_python_sdk.paths.batch_transactions_batch_id.get import GetBatchTransaction
from blue_snap_python_sdk.paths.transactions_transaction_id.get import GetById
from blue_snap_python_sdk.paths.alt_transactions_resolveorder_idorder_id.get import GetPaypalTransaction
from blue_snap_python_sdk.paths.agreements_prenotification_transaction_id.get import GetPreNotificationDebitAgreement
from blue_snap_python_sdk.paths.alt_transactions_transaction_id.get import GetSepaDd
from blue_snap_python_sdk.paths.alt_transactions_resolve.get import GetSofortTransaction
from blue_snap_python_sdk.paths.transactions_refund_transaction_id.post import InitiateRefund
from blue_snap_python_sdk.paths.alt_transactions.put import UpdatePaypalTransaction
from blue_snap_python_sdk.apis.tags.transaction_api_raw import TransactionApiRaw


class TransactionApi(
    ApproveMerchantTransaction,
    CancelPendingRefund,
    CreateBatchTransaction,
    CreateSofortTransaction,
    GetBatchTransaction,
    GetById,
    GetPaypalTransaction,
    GetPreNotificationDebitAgreement,
    GetSepaDd,
    GetSofortTransaction,
    InitiateRefund,
    UpdatePaypalTransaction,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: TransactionApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = TransactionApiRaw(api_client)
