# coding: utf-8

"""
    API Settings

    At BlueSnap, we look at payments a little differently. Our Payment Orchestration Platform helps businesses accept payments globally and is designed to increase revenue and reduces costs. We provide a comprehensive back-end solutions that simplifies the complexity of payments, managing the full process from start to finish.  BlueSnap supports payments through multiple sales channels such as online and mobile sales, marketplaces, subscriptions, invoice payments and manual orders through a virtual terminal. And for businesses looking for embedded payments, we offer white-labeled payments for platforms with automated underwriting and onboarding that supports marketplaces and split payments.  And with one integration and contract, businesses can sell in over 200 geographies with access to local acquiring in 47 countries, 110+ currencies and 100+ global payment types, including popular eWallets, automated accounts receivable, world-class fraud protection and chargeback management, built-in solutions for regulation and tax compliance, and unified global reporting to help businesses grow.  With a US headquarters in Waltham, MA, and EU headquarters in Dublin, Ireland, BlueSnap is backed by world-class private equity investors including Great Hill Partners and Parthenon Capital Partners.   Learn more at BlueSnap.com

    The version of the OpenAPI document: 8976-Tools
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from blue_snap_python_sdk.type.transaction_create_sofort_transaction_request_acss_direct_debit_transaction import TransactionCreateSofortTransactionRequestAcssDirectDebitTransaction
from blue_snap_python_sdk.type.transaction_create_sofort_transaction_request_becs_direct_debit_transaction import TransactionCreateSofortTransactionRequestBecsDirectDebitTransaction
from blue_snap_python_sdk.type.transaction_create_sofort_transaction_request_ecp_transaction import TransactionCreateSofortTransactionRequestEcpTransaction
from blue_snap_python_sdk.type.transaction_create_sofort_transaction_request_ideal_transaction import TransactionCreateSofortTransactionRequestIdealTransaction
from blue_snap_python_sdk.type.transaction_create_sofort_transaction_request_local_bank_transfer_transaction import TransactionCreateSofortTransactionRequestLocalBankTransferTransaction
from blue_snap_python_sdk.type.transaction_create_sofort_transaction_request_payer_info import TransactionCreateSofortTransactionRequestPayerInfo
from blue_snap_python_sdk.type.transaction_create_sofort_transaction_request_paypal_transaction import TransactionCreateSofortTransactionRequestPaypalTransaction
from blue_snap_python_sdk.type.transaction_create_sofort_transaction_request_sepa_direct_debit_transaction import TransactionCreateSofortTransactionRequestSepaDirectDebitTransaction
from blue_snap_python_sdk.type.transaction_create_sofort_transaction_request_sofort_transaction import TransactionCreateSofortTransactionRequestSofortTransaction

class RequiredTransactionCreateSofortTransactionRequest(TypedDict):
    pass

class OptionalTransactionCreateSofortTransactionRequest(TypedDict, total=False):
    ecpTransaction: TransactionCreateSofortTransactionRequestEcpTransaction

    amount: typing.Union[int, float]

    payerInfo: TransactionCreateSofortTransactionRequestPayerInfo

    softDescriptor: str

    currency: str

    authorizedByShopper: bool

    becsDirectDebitTransaction: TransactionCreateSofortTransactionRequestBecsDirectDebitTransaction

    idealTransaction: TransactionCreateSofortTransactionRequestIdealTransaction

    localBankTransferTransaction: TransactionCreateSofortTransactionRequestLocalBankTransferTransaction

    paypalTransaction: TransactionCreateSofortTransactionRequestPaypalTransaction

    acssDirectDebitTransaction: TransactionCreateSofortTransactionRequestAcssDirectDebitTransaction

    sepaDirectDebitTransaction: TransactionCreateSofortTransactionRequestSepaDirectDebitTransaction

    sofortTransaction: TransactionCreateSofortTransactionRequestSofortTransaction

class TransactionCreateSofortTransactionRequest(RequiredTransactionCreateSofortTransactionRequest, OptionalTransactionCreateSofortTransactionRequest):
    pass
