# coding: utf-8

"""
    API Settings

    At BlueSnap, we look at payments a little differently. Our Payment Orchestration Platform helps businesses accept payments globally and is designed to increase revenue and reduces costs. We provide a comprehensive back-end solutions that simplifies the complexity of payments, managing the full process from start to finish.  BlueSnap supports payments through multiple sales channels such as online and mobile sales, marketplaces, subscriptions, invoice payments and manual orders through a virtual terminal. And for businesses looking for embedded payments, we offer white-labeled payments for platforms with automated underwriting and onboarding that supports marketplaces and split payments.  And with one integration and contract, businesses can sell in over 200 geographies with access to local acquiring in 47 countries, 110+ currencies and 100+ global payment types, including popular eWallets, automated accounts receivable, world-class fraud protection and chargeback management, built-in solutions for regulation and tax compliance, and unified global reporting to help businesses grow.  With a US headquarters in Waltham, MA, and EU headquarters in Dublin, Ireland, BlueSnap is backed by world-class private equity investors including Great Hill Partners and Parthenon Capital Partners.   Learn more at BlueSnap.com

    The version of the OpenAPI document: 8976-Tools
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from blue_snap_python_sdk import schemas  # noqa: F401


class TransactionCreateSofortTransactionRequest(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
        
            @staticmethod
            def ecpTransaction() -> typing.Type['TransactionCreateSofortTransactionRequestEcpTransaction']:
                return TransactionCreateSofortTransactionRequestEcpTransaction
            amount = schemas.Float32Schema
        
            @staticmethod
            def payerInfo() -> typing.Type['TransactionCreateSofortTransactionRequestPayerInfo']:
                return TransactionCreateSofortTransactionRequestPayerInfo
            softDescriptor = schemas.StrSchema
            currency = schemas.StrSchema
            authorizedByShopper = schemas.BoolSchema
        
            @staticmethod
            def becsDirectDebitTransaction() -> typing.Type['TransactionCreateSofortTransactionRequestBecsDirectDebitTransaction']:
                return TransactionCreateSofortTransactionRequestBecsDirectDebitTransaction
        
            @staticmethod
            def idealTransaction() -> typing.Type['TransactionCreateSofortTransactionRequestIdealTransaction']:
                return TransactionCreateSofortTransactionRequestIdealTransaction
        
            @staticmethod
            def localBankTransferTransaction() -> typing.Type['TransactionCreateSofortTransactionRequestLocalBankTransferTransaction']:
                return TransactionCreateSofortTransactionRequestLocalBankTransferTransaction
        
            @staticmethod
            def paypalTransaction() -> typing.Type['TransactionCreateSofortTransactionRequestPaypalTransaction']:
                return TransactionCreateSofortTransactionRequestPaypalTransaction
        
            @staticmethod
            def acssDirectDebitTransaction() -> typing.Type['TransactionCreateSofortTransactionRequestAcssDirectDebitTransaction']:
                return TransactionCreateSofortTransactionRequestAcssDirectDebitTransaction
        
            @staticmethod
            def sepaDirectDebitTransaction() -> typing.Type['TransactionCreateSofortTransactionRequestSepaDirectDebitTransaction']:
                return TransactionCreateSofortTransactionRequestSepaDirectDebitTransaction
        
            @staticmethod
            def sofortTransaction() -> typing.Type['TransactionCreateSofortTransactionRequestSofortTransaction']:
                return TransactionCreateSofortTransactionRequestSofortTransaction
            __annotations__ = {
                "ecpTransaction": ecpTransaction,
                "amount": amount,
                "payerInfo": payerInfo,
                "softDescriptor": softDescriptor,
                "currency": currency,
                "authorizedByShopper": authorizedByShopper,
                "becsDirectDebitTransaction": becsDirectDebitTransaction,
                "idealTransaction": idealTransaction,
                "localBankTransferTransaction": localBankTransferTransaction,
                "paypalTransaction": paypalTransaction,
                "acssDirectDebitTransaction": acssDirectDebitTransaction,
                "sepaDirectDebitTransaction": sepaDirectDebitTransaction,
                "sofortTransaction": sofortTransaction,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["ecpTransaction"]) -> 'TransactionCreateSofortTransactionRequestEcpTransaction': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["amount"]) -> MetaOapg.properties.amount: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["payerInfo"]) -> 'TransactionCreateSofortTransactionRequestPayerInfo': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["softDescriptor"]) -> MetaOapg.properties.softDescriptor: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["currency"]) -> MetaOapg.properties.currency: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["authorizedByShopper"]) -> MetaOapg.properties.authorizedByShopper: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["becsDirectDebitTransaction"]) -> 'TransactionCreateSofortTransactionRequestBecsDirectDebitTransaction': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["idealTransaction"]) -> 'TransactionCreateSofortTransactionRequestIdealTransaction': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["localBankTransferTransaction"]) -> 'TransactionCreateSofortTransactionRequestLocalBankTransferTransaction': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["paypalTransaction"]) -> 'TransactionCreateSofortTransactionRequestPaypalTransaction': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["acssDirectDebitTransaction"]) -> 'TransactionCreateSofortTransactionRequestAcssDirectDebitTransaction': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["sepaDirectDebitTransaction"]) -> 'TransactionCreateSofortTransactionRequestSepaDirectDebitTransaction': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["sofortTransaction"]) -> 'TransactionCreateSofortTransactionRequestSofortTransaction': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["ecpTransaction", "amount", "payerInfo", "softDescriptor", "currency", "authorizedByShopper", "becsDirectDebitTransaction", "idealTransaction", "localBankTransferTransaction", "paypalTransaction", "acssDirectDebitTransaction", "sepaDirectDebitTransaction", "sofortTransaction", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["ecpTransaction"]) -> typing.Union['TransactionCreateSofortTransactionRequestEcpTransaction', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["amount"]) -> typing.Union[MetaOapg.properties.amount, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["payerInfo"]) -> typing.Union['TransactionCreateSofortTransactionRequestPayerInfo', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["softDescriptor"]) -> typing.Union[MetaOapg.properties.softDescriptor, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["currency"]) -> typing.Union[MetaOapg.properties.currency, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["authorizedByShopper"]) -> typing.Union[MetaOapg.properties.authorizedByShopper, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["becsDirectDebitTransaction"]) -> typing.Union['TransactionCreateSofortTransactionRequestBecsDirectDebitTransaction', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["idealTransaction"]) -> typing.Union['TransactionCreateSofortTransactionRequestIdealTransaction', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["localBankTransferTransaction"]) -> typing.Union['TransactionCreateSofortTransactionRequestLocalBankTransferTransaction', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["paypalTransaction"]) -> typing.Union['TransactionCreateSofortTransactionRequestPaypalTransaction', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["acssDirectDebitTransaction"]) -> typing.Union['TransactionCreateSofortTransactionRequestAcssDirectDebitTransaction', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["sepaDirectDebitTransaction"]) -> typing.Union['TransactionCreateSofortTransactionRequestSepaDirectDebitTransaction', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["sofortTransaction"]) -> typing.Union['TransactionCreateSofortTransactionRequestSofortTransaction', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["ecpTransaction", "amount", "payerInfo", "softDescriptor", "currency", "authorizedByShopper", "becsDirectDebitTransaction", "idealTransaction", "localBankTransferTransaction", "paypalTransaction", "acssDirectDebitTransaction", "sepaDirectDebitTransaction", "sofortTransaction", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        ecpTransaction: typing.Union['TransactionCreateSofortTransactionRequestEcpTransaction', schemas.Unset] = schemas.unset,
        amount: typing.Union[MetaOapg.properties.amount, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        payerInfo: typing.Union['TransactionCreateSofortTransactionRequestPayerInfo', schemas.Unset] = schemas.unset,
        softDescriptor: typing.Union[MetaOapg.properties.softDescriptor, str, schemas.Unset] = schemas.unset,
        currency: typing.Union[MetaOapg.properties.currency, str, schemas.Unset] = schemas.unset,
        authorizedByShopper: typing.Union[MetaOapg.properties.authorizedByShopper, bool, schemas.Unset] = schemas.unset,
        becsDirectDebitTransaction: typing.Union['TransactionCreateSofortTransactionRequestBecsDirectDebitTransaction', schemas.Unset] = schemas.unset,
        idealTransaction: typing.Union['TransactionCreateSofortTransactionRequestIdealTransaction', schemas.Unset] = schemas.unset,
        localBankTransferTransaction: typing.Union['TransactionCreateSofortTransactionRequestLocalBankTransferTransaction', schemas.Unset] = schemas.unset,
        paypalTransaction: typing.Union['TransactionCreateSofortTransactionRequestPaypalTransaction', schemas.Unset] = schemas.unset,
        acssDirectDebitTransaction: typing.Union['TransactionCreateSofortTransactionRequestAcssDirectDebitTransaction', schemas.Unset] = schemas.unset,
        sepaDirectDebitTransaction: typing.Union['TransactionCreateSofortTransactionRequestSepaDirectDebitTransaction', schemas.Unset] = schemas.unset,
        sofortTransaction: typing.Union['TransactionCreateSofortTransactionRequestSofortTransaction', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'TransactionCreateSofortTransactionRequest':
        return super().__new__(
            cls,
            *args,
            ecpTransaction=ecpTransaction,
            amount=amount,
            payerInfo=payerInfo,
            softDescriptor=softDescriptor,
            currency=currency,
            authorizedByShopper=authorizedByShopper,
            becsDirectDebitTransaction=becsDirectDebitTransaction,
            idealTransaction=idealTransaction,
            localBankTransferTransaction=localBankTransferTransaction,
            paypalTransaction=paypalTransaction,
            acssDirectDebitTransaction=acssDirectDebitTransaction,
            sepaDirectDebitTransaction=sepaDirectDebitTransaction,
            sofortTransaction=sofortTransaction,
            _configuration=_configuration,
            **kwargs,
        )

from blue_snap_python_sdk.model.transaction_create_sofort_transaction_request_acss_direct_debit_transaction import TransactionCreateSofortTransactionRequestAcssDirectDebitTransaction
from blue_snap_python_sdk.model.transaction_create_sofort_transaction_request_becs_direct_debit_transaction import TransactionCreateSofortTransactionRequestBecsDirectDebitTransaction
from blue_snap_python_sdk.model.transaction_create_sofort_transaction_request_ecp_transaction import TransactionCreateSofortTransactionRequestEcpTransaction
from blue_snap_python_sdk.model.transaction_create_sofort_transaction_request_ideal_transaction import TransactionCreateSofortTransactionRequestIdealTransaction
from blue_snap_python_sdk.model.transaction_create_sofort_transaction_request_local_bank_transfer_transaction import TransactionCreateSofortTransactionRequestLocalBankTransferTransaction
from blue_snap_python_sdk.model.transaction_create_sofort_transaction_request_payer_info import TransactionCreateSofortTransactionRequestPayerInfo
from blue_snap_python_sdk.model.transaction_create_sofort_transaction_request_paypal_transaction import TransactionCreateSofortTransactionRequestPaypalTransaction
from blue_snap_python_sdk.model.transaction_create_sofort_transaction_request_sepa_direct_debit_transaction import TransactionCreateSofortTransactionRequestSepaDirectDebitTransaction
from blue_snap_python_sdk.model.transaction_create_sofort_transaction_request_sofort_transaction import TransactionCreateSofortTransactionRequestSofortTransaction
