# coding: utf-8

"""
    API Settings

    At BlueSnap, we look at payments a little differently. Our Payment Orchestration Platform helps businesses accept payments globally and is designed to increase revenue and reduces costs. We provide a comprehensive back-end solutions that simplifies the complexity of payments, managing the full process from start to finish.  BlueSnap supports payments through multiple sales channels such as online and mobile sales, marketplaces, subscriptions, invoice payments and manual orders through a virtual terminal. And for businesses looking for embedded payments, we offer white-labeled payments for platforms with automated underwriting and onboarding that supports marketplaces and split payments.  And with one integration and contract, businesses can sell in over 200 geographies with access to local acquiring in 47 countries, 110+ currencies and 100+ global payment types, including popular eWallets, automated accounts receivable, world-class fraud protection and chargeback management, built-in solutions for regulation and tax compliance, and unified global reporting to help businesses grow.  With a US headquarters in Waltham, MA, and EU headquarters in Dublin, Ireland, BlueSnap is backed by world-class private equity investors including Great Hill Partners and Parthenon Capital Partners.   Learn more at BlueSnap.com

    The version of the OpenAPI document: 8976-Tools
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from blue_snap_python_sdk import schemas  # noqa: F401


class TransactionInitiateRefundRequestTransactionMetaDataMetaData(
    schemas.ListSchema
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        @staticmethod
        def items() -> typing.Type['TransactionInitiateRefundRequestTransactionMetaDataMetaDataItem']:
            return TransactionInitiateRefundRequestTransactionMetaDataMetaDataItem

    def __new__(
        cls,
        arg: typing.Union[typing.Tuple['TransactionInitiateRefundRequestTransactionMetaDataMetaDataItem'], typing.List['TransactionInitiateRefundRequestTransactionMetaDataMetaDataItem']],
        _configuration: typing.Optional[schemas.Configuration] = None,
    ) -> 'TransactionInitiateRefundRequestTransactionMetaDataMetaData':
        return super().__new__(
            cls,
            arg,
            _configuration=_configuration,
        )

    def __getitem__(self, i: int) -> 'TransactionInitiateRefundRequestTransactionMetaDataMetaDataItem':
        return super().__getitem__(i)

from blue_snap_python_sdk.model.transaction_initiate_refund_request_transaction_meta_data_meta_data_item import TransactionInitiateRefundRequestTransactionMetaDataMetaDataItem
